defaults: &defaults
  access_key_id: "devkey"
  secret_access_key: "devkey"
  bucket: "bucket"
  region: "region"
development:
  <<: *defaults
test:
  <<: *defaults
production:
  access_key_id: <%=ENV["AWS_ACCESS_KEY_ID"]%>
  secret_access_key: <%=ENV["AWS_SECRET_ACCESS_KEY"]%>
  bucket: "upload-s3-demo"
  region: "ap-southeast-1"