default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: upload-s3-demo_development
  host: localhost
  username: postgres
  password: root

test:
  <<: *default
  adapter: sqlite3
  pool: 5
  timeout: 5000
  database: db/test.sqlite3

production:
  <<: *default
  database: upload-s3-demo_production
  username: upload-s3-demo
  password: <%= ENV['UPLOAD-S3-DEMO_DATABASE_PASSWORD'] %>
